version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    restart: always 
    ports:
    - "5000:5000"
    volumes:
      - ./backend:/app/backend
  
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    restart: always 
    ports:
    - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
  

