FROM python:3.10-slim

WORKDIR /app/backend

COPY requirements.txt requirements.txt 
RUN pip3 install -r requirements.txt

COPY . /app/backend

ENV PYTHONDONTWRITEBYTECODE 1
ENV FLASK_APP=app.py 

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]

